spiral-project/ihatemoney

budget/models.py
Otherwise, the mysql sqlalchemy connector complains (cause VARCHAR2 of MySQL should have a max size defined).
For information, I made this change to package ihatemoney for [yunohost](https://yunohost.org)
=> specified sizes for string columns for MySQL

budget/default_settings.py, budget/requirements.txt, budget/run.py
… as it changed upstream for flask-mail>=0.8
Note that it breaks default installation (as reported in #120).
For the record, this change has been made very quiet at flask-mail, see https://github.com/mattupstate/flask-mail/issues/51
=> nicely deprecates DEFAULT_MAIL_SENDER 

budget/models.py
In some cases, settle algorithm failed to deliver optimal solution due to a rounding bug. Spotted by @sschnug. See this discussion (https://github.com/spiral-project/ihatemoney/pull/96) for more information.
I'm not sure this is the correct way to fix this. The better solution will be to use Decimal type instead of float type to store currency.
Unfortunatly, this involve quite a lot of changes, and maybe a migration strategy for actual database.
=> Bugfix rounding settle algorithm

README.rst, budget/default_settings.py, budget/run.py, budget/tests.py, budget/utils.py
For information, I made that change to be able to package a ihatemonney app for  [yunohost project](https://yunohost.org/).
Flask handles the cookie scoping to the url prefix via the [APPLICATION_ROOT](flask.pocoo.org/docs/0.10/config/) setting.
=> Made an URL prefix configurable in settings

budget/default_settings.py, budget/merged_settings.py, budget/run.py, budget/tests.py
Loading not versionned settings.py during tests make them less predictable. (Stumbled upon issues working on tests for #122 )
=> Do not load user-overriden settings in unit tests.

README.rst, budget/migrations/env.py
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
=> Convert readthedocs links for their .org -> .io migration for hosted projects

.travis.yml, README.rst
Add a travis.yml file to enable Continuous Integration with Travis CI (https://travis-ci.org/)
Currently two tests are failing so the build is not green, but environment setup and tests are properly executed by Travis.
=> Enable Travis CI

budget/models.py
When viewing the list of bills, bills are (correctly) sorted by date.  But
the order of all bills for a given day is not intuitive: I would expect
bills to be sorted by reverse order of insertion.  That is, the last bill
to be added for a given day should appear first, not last.  Otherwise,
when adding several bills in a row for a given day, it's confusing to see
that the new bills do not appear on top of the list.
Fix this by sorting by decreasing ID after sorting by date.
=> Sort bills by (date.desc, ID.desc) instead of just date.desc

budget/models.py, budget/templates/list_bills.html, budget/templates/settle_bills.html, budget/tests.py
These are workarounds for rounding issues.
=> Fix zero-amount transfers and other rounding issues

budget/models.py, budget/web.py
These two commits mostly fix issue #159.
=> Optimise sql queries

budget/tests.py
The test was always failing, actual reason is the `app.run.configure()` fails
to reset the `APPLICATION_ROOT` setting which `ServerTestCase.test_prefixed`
overloads (side effect).
This patch *do not* fix app.run.configure as it seems uneasy, but takes a
different approach which has the advantage of making the test more explicit.
Would still be a good thing to investigate more on configure().
Fix #163
=> Fix ServerTestCase.test_unprefixed test

.travis.yml
So that we are consistent between dev test env and CI test env.
The use of `TOXENV` is to keep travis running the several envs in parallel.
=> Make travis use tox

.travis.yml, budget/utils.py, tox.ini
Note that py3.4 is the version shipped in current Debian version (Jessie).
~That's a WIP, because it will need to be rebased (and modified) after #186 gets merged.~ DONE
=> Add Python 3.4 support

budget/default_settings.py, budget/templates/home.html, budget/tests/tests.py, budget/web.py
When set to False (True by default), it deactivates
the demo project
=> Add ACTIVATE_DEMO_PROJECT setting

budget/templates/layout.html
I've just realized it was missing a `meta` tag.
Still not perfect, but incidentally it fixes #219.
Footer can be truncated on small screen, I do not have quick fix for this :/
=> Add meta viewport tag

ihatemoney/default_settings.py, ihatemoney/tests/tests.py
In flask's development server, the route handlers
run in a different thread than the main thread
thus an in-memory database created in the main thread
cannot be acccessed by the route handlers.
Switching the default database location to a temporary
file solves the isssue.
See full explanation here:
https://gehrcke.de/2015/05/in-memory-sqlite-database-and-flask-a-threading-trap/
=> Fix #248: Database creation issue

ihatemoney/templates/layout.html, ihatemoney/templates/list_bills.html
Bootstrap-datepicker is only included in the
list_bills template but its configuration was
living in the layout template, leading to a
javascript error on every page except list_bills.
Fixes #256
=> Fix misplaced datepicker configuration

docs/installation.rst
Reality-sync with default_settings.py
Not fixing the whole table layout because
- my text editor doesn't do it ;
- I'm too lazy ;
- #251 is IMHO the real way to this issue :)
=> Fix default SQLALCHEMY_DATABASE_URI value in doc

conf/supervisord.conf
To match `budget` name disparition (package got renamed in #243).
This should be mentioned in upgrade guide.
ref #243 #264 
Is this housekeeping night ? :-)
=> BREAKING CHANGE: Rename supervisor program

docs/installation.rst, ihatemoney/run.py
Also add a warning at runtime if database is stored under `/tmp`.
This fixes #266.
=> Update installation doc to include doc about production values

CHANGELOG.rst, ihatemoney/api.py, ihatemoney/forms.py, ihatemoney/migrations/versions/b78f8a8bdb16_hash_project_passwords.py, ihatemoney/templates/reminder_mail.en, ihatemoney/templates/reminder_mail.fr, ihatemoney/tests/tests.py, ihatemoney/web.py
- Remove all occurences of clear text project passwords.
- Migrate the database to hash the previously stored passwords.
Closes #232
=> Use hashed passwords for projects

ihatemoney/static/css/main.css, ihatemoney/templates/list_bills.html
Unless there is a good reason to keep the JS version.
=> Replace some CSS by some JS

ihatemoney/templates/layout.html
{% block sidebar %} is used by sidebar_table_layout.html and its children, not by
layout.html nor its direct children.
This is dead code removal.
=> Remove un-needed sidebar block

CHANGELOG.rst, ihatemoney/api.py, ihatemoney/tests/tests.py
Before that commit, every PUT *must* change the name of the members, so that was:
- no idempotence,
- no ability to change only weight
fix #295
(for the story, it took me more time to write #295 yesterday than to fix the bug today :p)
=>  Fix PUT api/project/:code/members/:id

ihatemoney/manage.py
Avoid confusing the user for commands outputing text.
That is quite of a hack, but at least it is simple.
I tried several other approaches, but they proved overly complicated (involving big refactoring, inheritance madness, or removing commands, or even having to deal with metaclasses…).
=> Silent stderr output during app init for some commands

ihatemoney/tests/tests.py
Bad inheritance was causing APITestsCase tests to be ran twice.
=> Fix tests layout so that API tests are not ran twice

Dockerfile, conf/confandrun.sh, docs/installation.rst
- Use exec to run gunicorn and avoid creating a new process.
- Add the possibility to pass any additional parameters to
gunicorn.
- Use only one gunicorn worker by default as the usual way to
scale the app in production would be to use the scale command
of the cluster scheduler. Additional workers could still be
added by passing the "-w" gunicorn parameter to docker run.
=> Fix some anti patterns in docker deployment

ihatemoney/conf-templates/apache-vhost.conf.j2, ihatemoney/manage.py
`python-home` is prefered over `python-path`. It will work with or without
a virtualenv.
See http://modwsgi.readthedocs.io/en/develop/configuration-directives/WSGIDaemonProcess.html
=> Fix Apache conf template, without relying on environment var

CHANGELOG.rst, docs/installation.rst
PyMySQL is more difficult to install since its version 0.9 since it now depends
on *cryptography* lib, which in turns depends on OpenSSL and Python dev files.
See https://github.com/PyMySQL/PyMySQL/issues/697
side-note : I am pretty sure it breaks the docker setup, but I do not use docker, anyone to check and fix ? @0livd ?
=> Document MySQL setup

Dockerfile
The Python cffi package requires the libc, libffi and openssl
development packages, as well as gcc to compile it.
These packages are not included in the alpine image by default.
=> Fix cffi installation in Dockerfile

CHANGELOG.rst, ihatemoney/forms.py, ihatemoney/utils.py, requirements.txt
With the introduction of email_validator, the wtform API changed, and the validation of email fields was broken in the invitation mechanism.
This pull request hopefully fixes this, and at the same time make all the tests pass on our CI.
=> Fix failing tests

README.rst
Hi there! Since it took me around 15 minutes to discover the Contributing page on the documentation site (I started by looking at the Makefile and other places, and figured out the listening port after trial and error and looking up what the default for Flask was), how about we add a small Contributing section in the readme file, just linking to the documentation website? :slightly_smiling_face:
=> Add a contributing section to the readme file

Makefile
Add help target to the Makefile
It is often expected to have a `help` target in a Makefile. This one is
automatically generated from comments in the Makefile so it is easier to
maintain.
This commit only documents targets that seem the most important.
---
Add the server address and port on `make serve`
Developers should not have to read the documentation to find where to
point their browsers to access ihatemoney application.
---
Add .PHONY instructions to the Makefile
`.PHONY` instructs Make to not look, for instance, for an `install` file
before executing the corresponding target. If such a file would exist,
the command would not be performed at all. This is because Make is
initially intended to create files (i.e. targets) and consider there is
nothing to do if the file already exists.
=> doc: Improve Makefile

ihatemoney/web.py
When double-clicking on the delete button, the first click actually
deletes the bill, and the second click does the same action again. But
as the bill is already deleted, it displays a 404 page which can be
misleading.
This fix makes the app trigger a redirect when the bill seem to doesn't
exist, fixing this strange behaviour.
=> Fix double-click when deleting a bill (#349)

ihatemoney/templates/display_message.html, ihatemoney/templates/password_reminder_sent.html, ihatemoney/web.py
Create a new route with a new generic page that display a title and a message on a <p> tag. This route will be triggered after succesfully submit password reminder form
See issue #455
=> fix: display validation message on password reminder

docs/contributing.rst
I have tried to follow instructions in https://ihatemoney.readthedocs.io/en/latest/contributing.html in order to run the server.
It has been impossible to configure it. Finally I have discovered that the errors was that ihatemoney module should be installed before run "python run.py".
I have updated the documentation in order to reflect it.
=> Added install of ihatemoney module to documentation

ihatemoney/forms.py, ihatemoney/static/css/main.css, ihatemoney/static/css/tagsinput.css, ihatemoney/static/js/tagsinput.js, ihatemoney/templates/layout.html, ihatemoney/templates/send_invites.html
Support for adding emails as tags.
Now you can paste an email list of comma-separated, tab-separated, semicolon-separated
and the input will render each email as a tag.
Also, you can enter emails in the input and use any of those characters in order to create an email tag. Finally, if you enter an email and click enter it will create a tag.
I have added support to not allow duplicates.
=> Added support to split invitation emails #133

ihatemoney/api.py, ihatemoney/tests/tests.py
Fixed changes advised by @almet in #500
=> Token support

ihatemoney/templates/list_bills.html
-As @almet suggested adding `data-keyboard = "false"` prevents the bill from being cancelled when hitting the `ESC` key to cancel out of autocomplete
=> prevent bill cancellation when cancelling autocomplete

ihatemoney/models.py, ihatemoney/static/css/main.css, ihatemoney/templates/statistics.html, ihatemoney/web.py
When used as a monthly expenses tracker (without the requirement for settling) this tool lacks an overview. This is a WIP initial attempt to add a monthly overview of all expenses.
This is my first version:
I do not believe it is ready to merge yet, but I wanted to get some feedback on the location of the new table, the design, should it also contain running/yearly totals, etc. 
Last but not least, is this a feature you even want? :) 
I'm looking forward to your feedback.
Edit: I know I still need to use the translation functions for the strings
=> Monthly expenses

ihatemoney/api/common.py, ihatemoney/api/v1/__init__.py, ihatemoney/api/v1/resources.py, ihatemoney/run.py
Note that no changes were made to the api, the code was refactored to allow for new versions of the api to be created down the road.
Here's what this would look like:
+-- api/
+-- v1/
+-- __init__.py
+-- resources.py
+-- v1_1/
+-- __init__.py
+-- resources.py
+-- v2/
+-- __init__.py
+-- resources.py
+-- __init__.py
+-- common.py
=> Added support for multiple API versions

ihatemoney/static/css/main.css, ihatemoney/templates/list_bills.html, ihatemoney/web.py
This is a work-in-progress proposal to paginate the list of bills. The main motivation is that I have 1095 bills, and the list of bills is starting to be slow to display!
Before investing time in design etc, I would like to first gather some feedback on the idea itself.
By default, the first page is displayed (most recent bills). Older bills can be displayed with the `page` URL parameter:
```
$URL/project/?page=42
```
Documentation for this feature in flask-sqlalchemy is here:
https://flask-sqlalchemy.palletsprojects.com/en/2.x/api/#flask_sqlalchemy.BaseQuery.paginate
https://flask-sqlalchemy.palletsprojects.com/en/2.x/api/#flask_sqlalchemy.Pagination
Some things to improve:
- decide on the number of bills to display on each page (20 items by default, which is probably fine)
- decide what …
=> Paginate the list of bills

ihatemoney/static/css/main.css, ihatemoney/templates/statistics.html, ihatemoney/tests/tests.py
The table in sidebar is now aligned with the one in content, to avoid
redundant informations.
All tables are back to normal on small devices.
=> Align tables in statistics

ihatemoney/run.py, ihatemoney/web.py
to maintain language preference
=> updated web.py to make session permanent

docs/contributing.rst
The following changes were done:
- move "How to contribute" first, and "Set up a dev environment" as the second section.  This way, a new contributor has access to the most general information first, instead of the very specific "dev environment" documentation.
- reduce "How to contribute" / "As a developer" by moving the part about tests to a new "Contributing as a developer" section (see below).  This way, all types of contributions get roughly the same amount of text in the first "How to contribute" section.
- add a new "Contributing as a developer" section, which lists items that are useful when preparing a code contribution (running tests, formatting code, create database migration).  These items were moved either from "How to contribute" or from "Set up a dev environment".
I also …
=> Reorganize "Contributing" documentation to be more accessible to new contributors

ihatemoney/messages.pot, ihatemoney/templates/history.html, ihatemoney/translations/cs/LC_MESSAGES/messages.po, ihatemoney/translations/de/LC_MESSAGES/messages.po, ihatemoney/translations/el/LC_MESSAGES/messages.po, ihatemoney/translations/es_419/LC_MESSAGES/messages.po, ihatemoney/translations/fr/LC_MESSAGES/messages.po, ihatemoney/translations/id/LC_MESSAGES/messages.po, ihatemoney/translations/nb_NO/LC_MESSAGES/messages.po, ihatemoney/translations/nl/LC_MESSAGES/messages.po, ihatemoney/translations/tr/LC_MESSAGES/messages.po, ihatemoney/translations/uk/LC_MESSAGES/messages.po, ihatemoney/translations/zh_HANS-CN/LC_MESSAGES/messages.po
There are a couple of translations that seems broken to me.
=> Fix translations.

ihatemoney/models.py, ihatemoney/tests/tests.py
Currently the string representation of a Bill is: `<amount> for <description>`
It is used in the History Page to describe changes that were applied to Bills, for instance:
Bill "42.0 for Test" renamed to "Another Test"
This is inconsistent, not easy to read, and the "for" in the middle is not translatable.
To solve this issue, simply switch the string representation of a bill to its description.
=> Fix string representation of bills

ihatemoney/utils.py
Currently, norwegian (nb_NO) displays as "None" in the language change
select (upper right corner of the UI).
This is because language codes were not parsed correctly when they contain "_".
Here is a summary of the changes for the languages we support, before:
```
>>> Locale('nb_NO')
Locale('nb_NO')
>>> Locale('nb_NO').display_name
None
>>> Locale('es_419')
Locale('es', territory='419')
>>> Locale('es_419').display_name
'español latinoamericano'
>>> Locale('zh_HANS-CN')
babel.core.UnknownLocaleError: unknown locale 'zh_HANS-CN'
>>> Locale('zh_HANS-CN').display_name
babel.core.UnknownLocaleError: unknown locale 'zh_HANS-CN'
```
After:
```
>>> Locale.parse('nb_NO')
Locale('nb', territory='NO')
>>> Locale.parse('nb_NO').display_name
'norsk bokmål (Norge)'
>>> Locale.parse('es_419') …
```
=> Fix language code parsing

ihatemoney/utils.py, ihatemoney/web.py
Currently we only have email templates for French and English.  Setting
the current locale to any other language generates an exception when
creating a project, because Flask can't find the template file.
Fix this by falling back to English if no language-specific template file
is found.
=> Fix crash when a localized email template is missing

ihatemoney/templates/layout.html, ihatemoney/web.py
It is now possible to specify a category when calling `flash()` to change
the color of the alert box.  The default category is interpreted as
"success" for backwards compatibility.  For now, we only use the
additional "danger" category to show errors.
The available categories are the Bootstrap contextual classes listed here:
https://getbootstrap.com/docs/4.0/components/alerts/
=> Add support for different categories of "flash alerts"

ihatemoney/templates/statistics.html, ihatemoney/tests/tests.py
This fixes #607 and add a test case for this bug.
It also renames participants in test cases to avoid alphabetical ordering.
Inserting participants in alphabetical order is a special case, because ordering by ID will be the same as ordering by name.  This is a bad idea in test cases, as #607 has shown.
=>  Fix order of participants in the statistics page

ihatemoney/currency_convertor.py, ihatemoney/forms.py, ihatemoney/migrations/versions/927ed575acbd_add_currencies.py, ihatemoney/run.py, ihatemoney/templates/forms.html, ihatemoney/templates/list_bills.html, ihatemoney/utils.py, ihatemoney/web.py
Improve #541 by adding the following:
- Rename "No Currency" to ISO4217 "XXX"
- Use Babel to render currency symbols and names in currency lists
- Improve i18n in bill lists
Fix #601 #600 
I discovered Babel number formatting functions, and they are awesome. They are wrapped by flask_babel, undocumented as far as I know.
=> Improve currencies

ihatemoney/templates/settle_bills.html, ihatemoney/templates/statistics.html, ihatemoney/tests/tests.py
This should unify the number formats, along with #618
=> use currency format everywhere

ihatemoney/messages.pot, ihatemoney/tests/tests.py, ihatemoney/translations/cs/LC_MESSAGES/messages.po, ihatemoney/translations/de/LC_MESSAGES/messages.po, ihatemoney/translations/el/LC_MESSAGES/messages.po, ihatemoney/translations/es_419/LC_MESSAGES/messages.po, ihatemoney/translations/fr/LC_MESSAGES/messages.po, ihatemoney/translations/id/LC_MESSAGES/messages.po, ihatemoney/translations/it/LC_MESSAGES/messages.po, ihatemoney/translations/nb_NO/LC_MESSAGES/messages.po, ihatemoney/translations/nl/LC_MESSAGES/messages.po, ihatemoney/translations/pl/LC_MESSAGES/messages.po, ihatemoney/translations/ru/LC_MESSAGES/messages.po, ihatemoney/translations/tr/LC_MESSAGES/messages.po, ihatemoney/translations/uk/LC_MESSAGES/messages.po, ihatemoney/translations/zh_HANS-CN/LC_MESSAGES/messages.po, ihatemoney/utils.py, ihatemoney/web.py
In one case, we were not catching a family of possible exceptions
(socket.error), and in the two other cases there was no error handling at
all.  Sending emails can easily fail if no email server is configured, so
it is really necessary to handle these errors instead of crashing with a
HTTP 500 error.
Refactor email sending code and add proper error handling.
Show alert messages that tell the user if an email was sent or if there
was an error.
When sending a password reminder email or inviting people by email, we
don't proceed to the next step in case of error, because sending emails is
the whole point of these actions.
=> Improve error handling when sending emails

ihatemoney/run.py, ihatemoney/templates/list_bills.html, ihatemoney/templates/settle_bills.html, ihatemoney/templates/sidebar_table_layout.html, ihatemoney/templates/statistics.html
This new context filter use the project default currency as default
currency. It is way cleaner.
It is in draft, waiting for #619 first.
=> Replace currencyformat_nc with currency filter

ihatemoney/static/css/main.css
I noticed on my iphone 6 that the card divs for the login forms were not central on the screen. It seems to be fixed by increasing the @media max width.
before:
after:
=> Changed @media max-width for .home .card to 450px to fix responsiveness

ihatemoney/conf-templates/apache-vhost.conf.j2
The current configuration generated uses the old syntax for Apache access control. On a Debian 10 install I recently did the generated config just resulted in an access denied error when using Apache and mod_wsgi. Making the changes in this pull request to my Apache config solved the issue (got the hint looking at Flask's documentation here: https://flask.palletsprojects.com/en/1.1.x/deploying/mod_wsgi/#configuring-apache).
=> Update apache-vhost config generation

ihatemoney/default_settings.py
Hi
I've just finished the translation into Japanese on Weblate,[https://hosted.weblate.org/projects/i-hate-money/i-hate-money/](url)
So I updated default_settings.py to add Japanese as one of the supported languages.
=> Add Japanese to the supported languages

docs/configuration.rst, ihatemoney/conf-templates/ihatemoney.cfg.j2, ihatemoney/history.py, ihatemoney/run.py, ihatemoney/templates/history.html, ihatemoney/templates/list_bills.html
See individual commits for details.
I'm not sure about this one. On the one hand, having localized date and time that follows the selected language is nice. On the other hand, the timezone issue (see 812efad22a9d3a07699feec681fccce52acc5442) means that it would make more sense to format date and time in Javascript, but then we would have less control over the formatting and it won't follow the selected language.
=> Localize dates and times

README.rst, docs/installation.rst, setup.cfg, tox.ini
Still use 3.8 for extensive tests.
=> Add python3.9 support

.travis.yml
Some dependencies (cryptography / cffi) starts requiring a rust compiler. However, using a more recent `pip` should download the correct wheel, prebuilt.
=> Fix travis build with python3.6

ihatemoney/currency_convertor.py
Fixes #735. The API we were using previously seems to now require an API key.
=> Change the URL of the exchange API. Fixes #735

tox.ini
See https://pycqa.github.io/isort/docs/upgrade_guides/5.0.0/#-recursive-or-rc for more info, but this flag isn't required anymore.
=> Remove obsolete isort flags

docs/contributing.rst, docs/requirements.txt, setup.cfg, tox.ini
Requirements for doc are now an extra require in setup.cfg
This enable a single place for dependencies, and faster CI jobs.
=> Using one job for all linting and doc generation

Makefile, docs/installation.rst, ihatemoney/manage.py, ihatemoney/tests/main_test.py, setup.cfg
Use flask.cli instead with compatibility layer for existing commands,
such as "runserver".
Flask-Script has been unmaintained for many years, and Flask-Migrate just removed support for it. Let's be mainstream!
=> remove usage of Flask-Script

ihatemoney/manage.py, ihatemoney/tests/main_test.py
Fix test by using the function that check password instead of just checking the output length. This length can be variable and will change with Werkzeug 2
=> Fix test for generate_hash_password

ihatemoney/forms.py, ihatemoney/run.py, ihatemoney/tests/budget_test.py, ihatemoney/tests/main_test.py, ihatemoney/web.py
One particular change for the method to find login_throttler. It was triggering a lot of deprecation warnings due to iterating over all known objects from the garbage collector.
=> Fix some deprecation warnings

ihatemoney/models.py
The previous query was working fine on sqlite and mariadb, but not on
postgresql :
return self.get_bills_unordered().group_by(Bill.original_currency).count() > 1
psycopg2.errors.GroupingError: column "bill.id" must appear in the GROUP BY clause or be used in an aggregate function
The failing SQL query was:
[SQL: SELECT count(*) AS count_1
FROM (SELECT bill.id AS bill_id, ...
FROM bill JOIN person ON person.id = bill.payer_id JOIN project ON project.id = person.project_id
WHERE bill.payer_id = person.id AND person.project_id = project.id AND project.id = %(id_1)s GROUP BY bill.original_currency) AS anon_1]
The problem is that sqlalchemy creates a subquery for postgresql, and the
internal query does not make sense.
GROUP BY is not actually useful, we simply need to count the number of …
=> Fix SQL query in has_multiple_currencies

.github/workflows/test-docs.yml, ihatemoney/tests/common/ihatemoney_testcase.py, ihatemoney/tests/ihatemoney.cfg, ihatemoney/tests/ihatemoney_envvar.cfg, ihatemoney/tests/main_test.py, setup.cfg, tox.ini
This is still a WIP to see if it works.
=> Enable CI builds with postgresql and mariadb

ihatemoney/tests/common/ihatemoney_testcase.py, ihatemoney/tests/main_test.py
Most of the tests are using a separate database, but we have a few tests
that are loading default values and are writing to /tmp/ihatemoney.db.
This is annoying because it's also the database used for development:
running the test suite breaks the dev database.
To fix this, always use a separate testing database to avoid interference.
=> tests: ensure that /tmp/ihatemoney.db does not get overwritten

.dockerignore, Dockerfile, conf/entrypoint.sh, docs/installation.rst
=> Change Dockerfile to compile python dependencies at build time.

ihatemoney/forms.py, ihatemoney/static/css/main.css, ihatemoney/templates/edit_project.html, ihatemoney/templates/forms.html, ihatemoney/templates/history.html, ihatemoney/templates/list_bills.html, ihatemoney/templates/sidebar_table_layout.html, ihatemoney/tests/budget_test.py, ihatemoney/tests/history_test.py, ihatemoney/utils.py, ihatemoney/web.py
This also switches all such actions to POST requests.
Remaining topics:
=> Add more validation to destructive actions (CSRF + additional password checking)

ihatemoney/templates/layout.html
Currently we remove the current language from the list.
Changing the list depending on the language is quite confusing, it's
better if it's always the same.
=> Display all languages in dropdown list, including current one

ihatemoney/run.py
Fix #803
On some systems, there is no configured local timezone, so LOCALTZ is
a fallback object, that don't fit use case for flask-babel.
Detect this and use 'UTC' instead
=> Fix unusable LOCALTZ

ihatemoney/messages.pot, ihatemoney/templates/layout.html, ihatemoney/translations/bn_BD/LC_MESSAGES/messages.po, ihatemoney/translations/cs/LC_MESSAGES/messages.po, ihatemoney/translations/de/LC_MESSAGES/messages.po, ihatemoney/translations/el/LC_MESSAGES/messages.po, ihatemoney/translations/eo/LC_MESSAGES/messages.po, ihatemoney/translations/es/LC_MESSAGES/messages.po, ihatemoney/translations/es_419/LC_MESSAGES/messages.po, ihatemoney/translations/fr/LC_MESSAGES/messages.po, ihatemoney/translations/hi/LC_MESSAGES/messages.po, ihatemoney/translations/id/LC_MESSAGES/messages.po, ihatemoney/translations/it/LC_MESSAGES/messages.po, ihatemoney/translations/ja/LC_MESSAGES/messages.po, ihatemoney/translations/ms/LC_MESSAGES/messages.po, ihatemoney/translations/nb_NO/LC_MESSAGES/messages.po, ihatemoney/translations/nl/LC_MESSAGES/messages.po, ihatemoney/translations/pl/LC_MESSAGES/messages.po, ihatemoney/translations/pt/LC_MESSAGES/messages.po, ihatemoney/translations/pt_BR/LC_MESSAGES/messages.po, ihatemoney/translations/ru/LC_MESSAGES/messages.po, ihatemoney/translations/sr/LC_MESSAGES/messages.po, ihatemoney/translations/sv/LC_MESSAGES/messages.po, ihatemoney/translations/ta/LC_MESSAGES/messages.po, ihatemoney/translations/tr/LC_MESSAGES/messages.po, ihatemoney/translations/uk/LC_MESSAGES/messages.po, ihatemoney/translations/zh_Hans/LC_MESSAGES/messages.po
In English, "software" is an [uncountable noun](https://dictionary.cambridge.org/grammar/british-grammar/uncountable-nouns). You could say "a free piece of software" or "some free software", but in this context it feels most natural to just drop the article entirely.
=> "a free software" -> "free software"

ihatemoney/forms.py
I suggest to be consistent with the question-style of our bill form.
Extra-bonus, this will be consistent with the expense table column names.
Isn't that beautiful ?
=> Consistently use questions in bill form

CHANGELOG.rst, ihatemoney/static/css/main.css, ihatemoney/templates/home.html
That occured on some screen sizes.
Example :
=> Avoid showcase-guy to point his finger at nothing

ihatemoney/templates/list_bills.html
Fixes #896
The clearfix should be applied before the pagination blocks.
=> Make the "Add a new bill" button visible on small resolutions.

ihatemoney/static/css/main.css, ihatemoney/templates/history.html, ihatemoney/templates/list_bills.html, ihatemoney/templates/sidebar_table_layout.html
Fixes #896
remove all 'float' buttons, replace them with nice flexboxes.
bill_table needs a flex-basis because with a very small width, it has a 0 height. I don't really know why, but adding a flex-basis: auto shows it.
=> sidebar_table_layout switches to flex column layout

ihatemoney/api/common.py, ihatemoney/tests/api_test.py, ihatemoney/tests/budget_test.py
=> Always authentify projects using a lowercase ID.

ihatemoney/static/css/main.css
If an alert is shown, any elements at the same height cannot be clicked, which is pretty frustrating, because it hides the "New Bill" button. This happens because the "messages" div is positioned absolutely with a width of 100%. 
This PR solves this issue by disabling pointer-events for that div and enabling them again specifically for alerts in that div.
=> Allow clicking buttons behind messages div

ihatemoney/api/common.py, ihatemoney/forms.py, ihatemoney/tests/main_test.py, ihatemoney/web.py
This was trickier than expected, due to some side effects : when the
captcha is set to `True` via configuration, it doesn't change the
behavior directly of the ProjectForm class, but does so only when the
project form is used in the `web.py` module.
So, when just using the API (and not using the web.py module, for
instance during tests — manual or functional), no problem was shown,
and everything was working properly.
But at soon as somebody sees the "/" endpoint, the captcha was
required, by both the API and the `web.py` module.
This fixes it by adding a way to bypass the captcha with a new
`bypass_captcha` property on the form.
=> Do not require a captcha when using the API

Dockerfile, ihatemoney/static/css/main.css
Two minor fixes :
- 68a4aa05e8f63ab1501a32ae3b39ad212c7d5c13 set `LEGAL_LINK` default value to "False", icon was displayed and redirected to /False if not overwritten
- displaying legal link in footer caused an overflow
Before :
After :
=> Legal link fixes

ihatemoney/static/css/main.css, ihatemoney/templates/layout.html, ihatemoney/templates/sidebar_table_layout.html
Fixes #903
They are now a macro, and can be called within other templates.
This give the ability to fit them anywhere, at the cost of template complexity.
=> Rework flash messages

docs/api.md, ihatemoney/api/common.py, ihatemoney/api/v1/resources.py, ihatemoney/tests/api_test.py
For #847 
Returns a list of supported currencies under `/api/currencies`.
This is my first PR for this project, any feedback is greatly appreciated :)
=> List supported currencies in API under api/currencies

ihatemoney/static/css/main.css, ihatemoney/templates/list_bills.html
When there are a lot of bills, this is much easier to access.
Before:
https://user-images.githubusercontent.com/297578/144515015-34d05c27-7117-4357-878f-4199b2172193.mp4
After:
https://user-images.githubusercontent.com/297578/144515040-21b74ca7-a02b-4198-856a-10a4ccd9d166.mp4
Notice also that the pagination and the "New bill button" is aligned with the "Add participant" field.
On mobile, since there are a lot of page, the pagination wrapping is not so nice, but it could be improved by changing "Next/Previous" label by using icon only on mobile.
=> Top pagination and new bill button are sticky

ihatemoney/models.py, ihatemoney/tests/budget_test.py, ihatemoney/web.py
Currently, we display a hard-coded "one year" range of monthly statistics
starting from today.  This generally is not the intended behaviour: for
instance, on an archived project, the bills might all be older than one
year, so the table only displays months without any operation.
Instead, display all months between the first and last bills.  There might
be empty months in the middle, but that's intended, because we want all
months to be consecutive.
If there are no bills, simply display an empty table.
=> Display monthly statistics for the range of months where the project was active

ihatemoney/models.py, ihatemoney/templates/list_bills.html, ihatemoney/tests/main_test.py, ihatemoney/web.py
Otherwise, we need to get the weight sum for each displayed bill.
Here, we are much more scalable.
With a pagination of 500, we previously had 507 queries if bill currencies were project's default, and nearly the double if not.
Now, we are down to 7.
On my Ryzen 4750G, Flask-debug toolbar profiler told me that displaying 500 out of 1000 bills drop from 2200ms to less than 1000ms.
More performance are expected in other PR.
Finally fixes #159 by continuing #161
=> [Performance] Get weight sum along with bills to scale

ihatemoney/templates/forms.html
Added tooltip to "How much?" field of add/edit bill to let users know about the possibility of computations.
screenshot:
=> Add a tooltip to advertize the computation trick on bills. (resolve  #985)

ihatemoney/forms.py, ihatemoney/tests/api_test.py, ihatemoney/tests/budget_test.py
see https://github.com/python-babel/babel/issues/821
fix #957
=> Check for too high values

ihatemoney/history.py, ihatemoney/models.py, ihatemoney/tests/history_test.py, ihatemoney/web.py
Fix #948
Note that there is no confirmation. The whole project is deleted right away, without any possibility to undo.
This is a bit of an anti feature from using SQLAlchemy-continuum, but the code can easily be adapted to delete the project history later.
=> Purge project history on deletion

docs/installation.md
Secure Session Cookies must be disabled when running things
locally and using localhost.
Fix #979.
=> Document cookies settings when using local Docker.

ihatemoney/tests/import_test.py, ihatemoney/utils.py
This is only needed for unsecure spreadsheet applications (hi Google Docs and MS Excel) that load formulae by default.
See https://owasp.org/www-community/attacks/CSV_Injection for some mitigation explanation. This is not complete, but it should be OK for now.
=> escape csv formulae

ihatemoney/static/css/main.css, ihatemoney/templates/list_bills.html
Completed feature request #1077 to use the double-click confirmation button that is also found in edit_project.html. This will prevent the accidental deletion of expenses (a destructive operation) with no warning.
=> Feature Request: Add a confirmation on expense deletion #1077

ihatemoney/static/css/main.css, ihatemoney/templates/dashboard.html, ihatemoney/tests/budget_test.py, ihatemoney/tests/common/ihatemoney_testcase.py, ihatemoney/web.py
This was broken due to changes introduced to make project deletion more secure. Rather than doing some complicated if branches, I decided this dashboard stuff is probably better handled with separate routes instead.
So I've reintroduced a way to delete the projects without specifying the project code (otherwise it's not possible for admins to do it).
=> Fix project deletion in the dashboard. Fixes #1094

ihatemoney/forms.py, ihatemoney/tests/api_test.py, ihatemoney/tests/budget_test.py
Bills with an amount of zero may be useful to remember that a transaction happened on a specific date, while the amount doesn't matter.
I use that with per-year projects when a reimbursement happens in year N but is relative to year N-1: I record it with an amount of zero in the project of year N, and with the real amount in the project of year N-1.
Besides, it's already possible to create such bills: while "0" is refused, "0.0" is accepted.  There are no visible issues with this kind of bills.
=> Allow bills with an amount of zero

.github/workflows/dockerhub.yml
I built an arm/v7 image locally with buildx and run it on my raspberry pi 3 successfully (https://hub.docker.com/r/greedybro/ihatemoney/tags)
Since the project CI is already using buildx via `docker/build-push-action@v2`, it should only require to had a list of architectures to build for.
The list should cover most of user needs with `armv7` for rapsberry 3 and before, and `arm64` for Mac with Apple silicon and raspberry 4 (and probabilly future models)
Closes  #1066
=> [CI] Build mutli-architecture docker image

ihatemoney/tests/budget_test.py, ihatemoney/web.py
=> Remember created project

ihatemoney/tests/budget_test.py, ihatemoney/web.py
=> Migrate existing sessions after conversion to dict

ihatemoney/templates/layout.html
The 404 page crashes when the user is logged in:
File "/home/zorun/code/ihatemoney/ihatemoney/templates/404.html", line 1, in top-level template code
{% extends "layout.html" %}
File "/home/zorun/code/ihatemoney/ihatemoney/templates/layout.html", line 124, in top-level template code
{{ g.logout_form.hidden_tag() }}
File "/home/zorun/venv/py3-ihatemoney/lib/python3.9/site-packages/jinja2/environment.py", line 474, in getattr
return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'flask.ctx._AppCtxGlobals object' has no attribute 'logout_form'
This is because the logout form is defined by a URL processor, and this does not seem to apply for all pages.
To solve this, simply skip the logout form if it's not defined.
=> Fix 404 page crash

ihatemoney/tests/api_test.py
Playing with the pytest branch I found that there were occurences of `self.assertTrue(200, resp.status_code)` style assertions in the tests. This really looks like someone intended to write `self.assertEqual` instead, as testing that any number is True will always pass :see_no_evil:
=> unit test assertion fixes

docs/api.md, docs/security.md, ihatemoney/forms.py, ihatemoney/templates/forms.html, ihatemoney/templates/send_invites.html, ihatemoney/tests/api_test.py, ihatemoney/tests/budget_test.py, ihatemoney/tests/history_test.py, ihatemoney/web.py
This is something we had documented in our [security documentation](https://ihatemoney.readthedocs.io/en/latest/security.html#giving-access-to-a-project), but we didn't actually do it...
As mentioned in this document, this has good security properties: you can invite somebody with an invitation link, and they will be able to access the project but not change the private code (because they don't know the current private code).
This new check also applies to all other settings (email address, history settings, currency), which is desirable.  Only somebody with knowledge of the private code can now change these settings.
Finally, document these security properties in the invitation page.
=> Require private code to edit a project settings, document better the invite options

docs/conf.py
The year of the documentation was 2021, with this PR it will take the current year of the documentation generation.
=> docs: dynamic year

CHANGELOG.md, docs/configuration.md, ihatemoney/forms.py, ihatemoney/manage.py, ihatemoney/models.py, ihatemoney/tests/budget_test.py, ihatemoney/tests/common/ihatemoney_testcase.py, ihatemoney/tests/ihatemoney.cfg, ihatemoney/tests/ihatemoney_envvar.cfg, ihatemoney/utils.py, ihatemoney/web.py
Adds two configuration parameters that are passed to generate_password_hash:
- PASSWORD_HASH_METHOD
- PASSWORD_HASH_SALT_LENGTH
The unit tests use high-speed low-security values and gain 50% speed.
fixes #1214
=> speed up unit tests

ihatemoney/templates/list_bills.html
This PR proposes three small changes to simplify adding a bill with only keyboard:
1. Makes the default focus on the "Add a new bill" button:
2. In the "Add a new bill" modal, makes the default focus on the first field:
3. Allows to escape the "Add a new bill" modal with the "Esc" key. (Was this intentionally deactivated?)
=> Simplifies adding a bill with keyboard only

.gitignore, ihatemoney/tests/api_test.py, ihatemoney/tests/budget_test.py, ihatemoney/tests/common/ihatemoney_testcase.py, ihatemoney/tests/conftest.py, ihatemoney/tests/history_test.py, ihatemoney/tests/import_test.py, ihatemoney/tests/main_test.py, setup.cfg
supersedes #1149 
closes #1148
This PR basically starts from 1149 and:
- adds pytest-flask for test readability
- replace setUp/tearDown with pytest fixtures
- rename test classes to use the pytest convention
- use pytest assertions
I suppose more could be done, for instance by moving away from the test class structure to a flat test files structure, and reorganize fixtures too, but maybe this is a good enough first step?
=> pytest migration

ihatemoney/history.py, ihatemoney/static/css/main.css, ihatemoney/templates/history.html
This PR add more details for bills in the history for each operation: insert, update, delete.
The idea is to be able to easily know what was a bill at some time (which can be difficult when it has been modified several times).
The PR also shorten long URL with an ellipsis `...` to avoid big overflows.
=> Add more details for bills in the history

ihatemoney/tests/budget_test.py, ihatemoney/web.py
Previously the last selected payer was lost when switching of project.
The structure of the variable `last_selected_payer` is changed (now it's a dictionary) then it has been renamed to `last_selected_payer_per_project` to avoid session bugs.
=> [Fix] Remember the last selected payer for each project

ihatemoney/tests/budget_test.py, ihatemoney/web.py
In short. Would you find nice to:
1. either remember the owers when adding several bills
2. or allow to define default owers in the settings of a project
?
(This PR implements 1.)
J'utilise régulièrement IHM dans un projet où je sélectionne toujours les mêmes "Pour qui ?" quand je saisi une facture. C'est un peu long de désélectionner à chaque fois.
Est-ce que vous seriez intéressés par une des propositions suivantes :
1. se rappeler, d'une facture sur l'autre, des derniers "Pour qui ?" sélectionnés (c'est actuellement le cas avec le "Qui a payé ?")
2. ou permettre de définir des "Pour qui ?" par défaut dans les paramètres du projet
?
Ma préférence va à 1 (interface plus légère). Et vous ?
(Cette PR implémente 1.)
=> Default owers when adding a bill

docs/api.md, ihatemoney/tests/api_test.py, ihatemoney/tests/budget_test.py, ihatemoney/tests/import_test.py, ihatemoney/tests/main_test.py
Swapping ‘Fred’ for ‘Jeanne’ across our docs and API.
Here’s the lowdown - 'Fred' and I ... we've got history. It's the kind of backstory that doesn't really gel with my day-to-day code jams. Every time I bump into 'Fred' in our project, it’s like a weird little jingle that gets stuck in my head – not the fun kind. So, I’m trading it out for 'Jeanne,' which is just a way chiller vibe for me.
But no worries, I’ve double-checked this swap, making sure it’s all smooth:
- All the 'Fred' references in the docs have waved goodbye, and 'Jeanne' has warmly taken their spot.
- If 'Fred' had a cameo in any comments, tests, or examples, 'Jeanne' is now nailing the audition instead.
- Gave the whole thing a once-over (then a twice-over) to catch any sneaky 'Fred' stragglers.
This isn’t about flipping …
=> Swapping Out 'Fred' for 'Jeanne' in Docs/API – Personal Peacekeeping 😊

docs/configuration.md
If the application is hosted on the path `/somestring`, static asset paths need to have prefix `/somestring/static/` but setting `APPLICATION_ROOT` to "somestring" will result in a relative path which will give a 4XX. Using "/somestring" fixes this.
e.g. static assets should look like this in source:
```html
<link rel="stylesheet" type="text/css" href="/somestring/static/css/main.css">
```
but without the leading slash they have `href="somestring/static/css/main.css"` which results in a network request for `{DOMAIN}/somestring/{PROJECT_NAME}/somestring/static/css/main.css`
The test suite includes the leading slash in `test_prefixed`:
https://github.com/spiral-project/ihatemoney/blob/76e8b3baf0b52d098c1287f01ebf30cdeeb6ecc5/ihatemoney/tests/main_test.py#L76-L77
---
Also fix default value, …
=> Fix APPLICATION_ROOT example in docs

.github/workflows/test-docs.yml, CHANGELOG.md, README.md, docs/installation.md, ihatemoney/tests/api_test.py, ihatemoney/tests/budget_test.py, pyproject.toml, tox.ini
This adds unit tests, CI, pypi classifiers and updates doc with support for python 3.12.
=> add support for python 3.12

MANIFEST.in
Since moving from ReST to Markdown, we forgot to update the manifest to include Markdown files.  It means that files such as README.md and CHANGELOG.md are missing from releases.  In practice, this broke the description on PyPI:
https://pypi.org/project/ihatemoney/6.1.3/
=> Fix missing markdown include in manifest

ihatemoney/babel.cfg
autoescape and with extensions are now built-in
to the Jinja2 compiler since v3.
See https://jinja.palletsprojects.com/en/3.1.x/changes/#version-3-0-0
=> [chore] Remove deprecated Jinja2 extensions.

ihatemoney/forms.py
This PR fixes #1291. 
It's a small fix to a small annoying bug : when a project as some bills, a default currency (different than "XXX") and you want to change the project settings an error message is shown : "Cannot change project currency because currency conversion is broken". The only way to change the project settings is then to remove the currency (set to "XXX"). Therefore, the error message is not constant with the behavior.
The default currency field is check against the current project default currency. If the project has bills and the new input default currency doesn't match the current one, the error "Cannot change project currency because currency conversion is broken" is shown. 
I have tested the behavior. This is true for the API as well as the GUI input.
=> Changing any settings is prevented when project has existing currency

ihatemoney/tests/budget_test.py, ihatemoney/tests/import_test.py, ihatemoney/web.py
This PR contains the changes requested after PR #1290 was merged. It contains only pretty minor changes.
Specifically this PR contains the following:
- Some tests contained leftover references to the "Transfer" type, these were removed. Also one test specifically checking the "Transfer" type has been completely removed.
- The actual terminology might change depending on the discussion in #1299 
- The `web.settle` route contained a "FIXME" comment. Looking into it, I think it was previously erroneously copied from `edit_bill` in web.py:811. It doesn't need to check if the bill belongs to the requested project as this function creates that bill itself.
- In one of the tests, "fromage" was removed. This erasure has been undone, and the vibes of the codebase have been improved.
- A test was …
=> Requested billtype changes

docs/installation.md
Had some issues with this for a while yesterday during the install process
Should clarify and help close #1321
Issue also found in #1169 and #334 where i found my solution
I added the last line about the example docker-compose being available because I didn't see it until i cloned the repo to update the doc for the $$
=> docs: add more details to installation process

ihatemoney/manage.py, ihatemoney/tests/main_test.py
I have edited two files for this functionality. The first is manage.py which uses the Click module to issue commands. The second is in main_test.py for testing. Let me know if you have any concerts / questions. Thank you, James.
=> working numProjects commandline functionality and unit tests

ihatemoney/history.py
This is a poor workaround to bug #1324.
It does not solve the issue but at least it avoid the "Internal server error", which is nice.
Now the bills for which payer or ower are not well versioned seem to:
If anyone has the same issue as me, I found a trick to make members well versioned: deactivate and reactivate them. The bills recorded afterward are well versioned.
=> Workaround to avoid history bug #1324

docs/contributing.md
Probably not perfect but better than nothing :-)
=> Update installation.md with uv dependency

ihatemoney/templates/forms.html
The "Bill type" field shouldn't be better placed in the "More options" section? What do you think?
I feel that it makes the UI clearer:
(works also in the /add and /edit pages)
=> Move the bill type field in the More options section

ihatemoney/templates/settle_bills.html
Little proposition to make the use of this button clearer ...
=> Add a tooltip to document the Settle button

ihatemoney/templates/sidebar_table_layout.html
Cases has been reported of rounding issues making deactivated users reapparing. This is due to the fact we're using floats (see #528 for details)
Fixes #1336
=> Do not display deactivated users when their balance is really small

ihatemoney/forms.py, ihatemoney/models.py, ihatemoney/templates/settle_bills.html, ihatemoney/tests/budget_test.py, ihatemoney/utils.py, ihatemoney/web.py
This is necessary to avoid XSS.  State-changing actions should never be done with a GET.
=> Change settle endpoint to use POST instead of GET

ihatemoney/models.py, ihatemoney/templates/statistics.html, ihatemoney/tests/api_test.py, ihatemoney/tests/budget_test.py
=> Add transferred/received amounts in statistics page
