AUTHORS, LICENSE, README.rst, budget/static/css/main.css, budget/templates/authenticate.html, budget/templates/forms.html, budget/templates/invitation_mail.en, budget/templates/list_bills.html, budget/templates/password_reminder.en, budget/templates/reminder_mail.en, budget/templates/send_invites.html, budget/tests.py, conf/nginx.conf, docs/_themes/pelican/static/pelican.css_t, docs/api.rst
Because it's good practice, and I'm tired of not removing the whitespaces fixes that my editor does from my commits.
=> Remove trailing whitespaces

budget/run.py
For some reason, the migration path from unmanaged db (from alembic
point-of-view) to managed db, through the initial migration works well with
sqlite… But not with mysql where the db system tries to re-create the existing
tables.
This commit is a way to detect if we are migrating from pre-alembic era and
skip the first migration (which would do nothing anyway), marking it as already
executed.
It's quite hackish but that's the best I found so far to get it working with
both MySQL and SQLite.
=> Fix migrations upgrade path for MySQL

docs/api.rst
Minor enhancements to the API doc.
=> REST API doc precisions

docs/api.rst
As the old domain seams dead and not even redirecting.
=> Change ihatemoney.notmyidea.org → ihatemoney.org

budget/tests.py
Test was Ok but failed due to some floating point errors.
=> Fix unit test rounding

budget/api.py, budget/forms.py, budget/models.py, budget/run.py, budget/web.py
Fix deprecation issues from travis log : 
https://s3.amazonaws.com/archive.travis-ci.org/jobs/194010192/log.txt
=> Fix deprecation issues (ExtDeprecationWarning)

budget/translations/fr/LC_MESSAGES/messages.po
=> Improve translation for user edit form.

budget/forms.py, budget/templates/forms.html, budget/templates/list_bills.html
Should fix #173 
I've rewritten `select_multi_checkbox` as an html template instead of a function. 
Arguments weren't properly escaped and this caused an XSS vulnerability.
=> Fix xss 173

.travis.yml, budget/forms.py, budget/models.py, budget/requirements.txt, budget/tests.py, budget/utils.py
Ihatemoney is now py2/3 compatible thanks to the six library
Based on what has been started in #158 
Porting the tests was a pain...
=> Py2/3 compatibility, 2nd round

budget/web.py
Use project.id in export filename as it is already slugified
=> Fix bad export filename

budget/run.py
=> Use app.root_path instead of __HERE__

budget/api.py, budget/default_settings.py, budget/forms.py, budget/manage.py, budget/tests.py, budget/utils.py, docs/conf.py, requirements.txt
We had a bunch of warnings yelling from ihatemoney code. That annoyed me both reading my production logs, dev environment, test environment and CI logs (example [here](https://travis-ci.org/spiral-project/ihatemoney/jobs/216129680) )
… And that's the point of warnings : annoying you till you actually fix them ;-)
That is what I did. Normally, these changes have no side effects, I bumped some dependencies versions, but to version numbers that were already picked on fresh installs (because we use `>=` to mark our dependencies versions).
I think there is still room for improvements (I have the feeling that the message from raven is not totally normal, or may at least be documented), but that is far enough for that PR :-)
=> Warnings hunt !

README.rst, conf/apache-vhost.conf, ihatemoney.wsgi
ihatemoney.wsgi is the entry point for mod_wsgi.
A virtualenv can be activated if its path is specified as
an env var in the apache virtual host file
=> Add the possibilty to run ihatemoney via Apache mod_wsgi

README.rst
Without this information, I really could not understand where to go next.
=> Update the README with additional requirements and information

Makefile
An alternative to the PR "fix-makefile", with an additional fix for looking up Python.
=> Fix makefile: Python lookup and virtualenv setup

README.rst, docs/requirements.txt
Otherwise Travis builds are failing ;)
=> Fix sphinx integration

budget/static/css/main.css, budget/templates/home.html, budget/templates/layout.html, budget/templates/sidebar_table_layout.html
This PR fixes the lack of responsive layout on mobile.
It should be ok on mobile devices for homepage and the main page of a given project, so that at least users could add new bills from a mobile device. Navbar on mobile device could still be enhanced though.
=> More responsive layout

conf/apache-vhost.conf, ihatemoney.wsgi
The path no longer needs to be modified in the .wsgi file
=> Tell Apache to add the budget directory to the python path

docs/requirements.txt
=> Update docs requirements to fix failing build

CHANGELOG.rst, CONTRIBUTORS
Not that I want to micro-review every single thing, but as this is the first time we put something in the changelog, that's to be sure you guys are ok with that.
I inspired from http://keepachangelog.com/en/0.3.0/,
The items list is made by hand, largely inspired (and copy/pasted) from the commit log.
What do you think ?
relates #180
=> Prepare changelog & contrib list for v1.0

CHANGELOG.rst, budget/manage.py, budget/run.py, budget/tests/tests.py, budget/web.py, docs/installation.rst
A generate_password_hash manage.py command is provided
Fixes #233
=> Use a hashed password for ADMIN_PASSWORD

budget/run.py
=> Warn user when using default 'not-so-secret' secret-key.

Makefile, budget/api.py, budget/forms.py, budget/manage.py, budget/run.py, budget/tests/tests.py, budget/web.py, dev-requirements.txt, tox.ini
I believe it will ease our life when it comes to packaging.
=> Make all imports relative

ihatemoney/tests/tests.py
Some supernatural power erased the configuration
tests, they're now back !
=> Revert configuration tests deletion

.gitignore, .travis.yml, README.rst, docs/installation.rst, requirements.txt, setup.py, tox.ini
=> Add python 3.6 support

CHANGELOG.rst
To bring some consistence / clarity to the changelog before releasing 2.0.
Please squash before merging, this meta-changes do not deserve such a big commit history :-)
=> Normalize changelog

docs/installation.rst
cc @Phyks and @JocelynDelalande
=> Add some information about Yunohost in the documentation.

MANIFEST.in, setup.py
In order to avoid duplicating the dependency list, as suggested by @Phyks. Can anyone review this? Thanks!
=> Parse requirements.txt in setup.py. Fix #273

CHANGELOG.rst, docs/index.rst, docs/installation.rst, docs/upgrade.rst
fix #274 
We were at risk of having an empty PR queue, so here is my attempt to fill it a bit ;-).
I'm hungry for comments/feedback, as I'm attaching importance to documentation :).
I think after this PR and #277 are last blockers for #264.
=> Add an upgrade guide

docs/api.rst, docs/installation.rst, docs/upgrade.rst, ihatemoney/tests/tests.py, ihatemoney/web.py
Fix some typos with the help of codespell (`pip install codespell`)
=> Fix some typos using codespell

docs/api.rst
=> Add missing properties in API docs

CHANGELOG.rst, ihatemoney/models.py, ihatemoney/tests/tests.py
=> Remove API password

ihatemoney/static/css/main.css, ihatemoney/templates/layout.html
Because I'm in the mood of killing some JS today :-)
=> Position flash messages with CSS rather than JS

ihatemoney/api.py, ihatemoney/tests/tests.py
*EDIT: since then, this is working*
This is not working yet, the `activated` state pushed via API seems not to be saved to DB. But I cannot figure out why.
Any ideas ? Help more than welcome.
I wrote a test, it shows how I would expect it to work.
=> Allow to disable/enable member via API

ihatemoney/conf-templates/apache-vhost.conf.j2
Added the couple of apache configuration lines necessary to get the basic authentication working for the API.
=> Enable basic auth passthrough for API

dev-requirements.txt, ihatemoney/manage.py, ihatemoney/tests/tests.py, tox.ini
In order to provide non-regression for #308.
=> manage commands testing

CHANGELOG.rst, ihatemoney/static/css/main.css
Make sidebar scrollable when there is an overflow.
=> Make sidebar scrollable

CHANGELOG.rst, ihatemoney/api.py, ihatemoney/run.py, ihatemoney/tests/tests.py, ihatemoney/utils.py, requirements.txt
The flask-rest custom json encoder is still needed and thus was added to ihatemoney's utils.
Closes #298
=> API: Migrate from flask-rest to flask-restful

Dockerfile
=> Docker: Fix gunicorn not using ihm system package

setup.py
hello,
I propose a simple fix for this issue : https://github.com/spiral-project/ihatemoney/issues/340
Have a good day
=> fix install with pip10

CHANGELOG.rst, ihatemoney/conf-templates/supervisord.conf.j2, ihatemoney/manage.py, ihatemoney/run.py
=> fix pbkdf2 check

Makefile, docs/contributing.rst, ihatemoney/messages.pot, ihatemoney/translations/fr/LC_MESSAGES/messages.po
Inspired by @Glandos work arround translation.
=> Enhance translation tooling

ihatemoney/run.py, requirements.txt
=> Remove Sentry, as it's not used anymore on prod.

ihatemoney/static/js/ihatemoney.js, ihatemoney/templates/forms.html
=> Simplify a JS function.

docs/installation.rst
It's easier to read, and easier to maintain. Fixes #251.
@JocelynDelalande if you can have a look ? Thanks !
=> Replace the settings table with multiple sections.

ihatemoney/static/css/main.css
=> Underline actions links on hover.

ihatemoney/manage.py, ihatemoney/tests/tests.py
=> Add a ihatemoney delete-project command.

ihatemoney/templates/forms.html
=> Fix form error on already existing participant.

CHANGELOG.rst, Makefile, docs/contributing.rst
=> Document database migrations

CHANGELOG.rst, ihatemoney/api.py, ihatemoney/tests/tests.py, requirements.txt
=> Add CORS to the API

ihatemoney/models.py, ihatemoney/tests/tests.py, ihatemoney/utils.py
=> Resolve "Update API project list"

ihatemoney/static/css/main.css, ihatemoney/templates/forms.html, ihatemoney/templates/home.html, ihatemoney/templates/layout.html, ihatemoney/templates/list_bills.html
Hi,
Here are a few small steps to improve the responsive situation.
I've start by removing some unused css properties, then adding some missing btn classes here and there.
Then adding responsive classes all around especially within the hamburger.
It's not perfect but better IMHO. I would have liked to rework more the nav bar but didn't want to change too much. I've only choose to put the dashboard inside the options instead of a plain nav item.
Let me know if there are things that does not work for you :)
before
after
Note: i've also added a prettier for the css file in a distinct commit, for better readability. I you want that i split the PR, let me know
=> Improve Responsive

ihatemoney/static/js/locales/bootstrap-datepicker.fr.min.js
because it doesn't need to be there :)
=> remove console log

Dockerfile, conf/entrypoint.sh
See commit message. Alternatively, the non-Nightly version could just download what's on Pypi; I don't have a clear criteria of choice here.
=> [docker] Add fixed release vs Nightly mode

ihatemoney/templates/send_invites.html
follow up of #451
didn't pushed it completely 🤕 
here is the end of it ...
sorry again
=> fix: add table layout for sharing options

Makefile, docs/contributing.rst
Fix #458 
The target is open for more compressions, if it's ever required some day…
=> Zopfli in makefile

README.rst, setup.py
=> Use codecs.open rather than open.

ihatemoney/templates/password_reminder_sent.html, ihatemoney/web.py
Let's allow the link to be translated, 
and also make sure that the string is extracted in setting it inline... no need for a var here.
=> Move translations in template and translate link

.gitignore, CHANGELOG.rst, ihatemoney/models.py, ihatemoney/tests/tests.py, requirements.txt, setup.py
Coded and reviewed while pairing with @Natim
=> Fix #434 Use the debts lib to solve settlements.

ihatemoney/api.py
In sharing options, we have a link with a token.
It might be a good idea to have, as API auth method, this token.
so apps can catch those links and use it directly
I think this is probably not enough because it doesn't let the app discover the project id ...
not sure if we need to include some endpoint that does : token => project id
or include project id in clear text in the url...
=> api: add bearer token support

ihatemoney/messages.pot, ihatemoney/templates/list_bills.html, ihatemoney/translations/el/LC_MESSAGES/messages.po, ihatemoney/translations/es_419/LC_MESSAGES/messages.po, ihatemoney/translations/fr/LC_MESSAGES/messages.po, ihatemoney/translations/nb_NO/LC_MESSAGES/messages.po, ihatemoney/translations/nl/LC_MESSAGES/messages.po, ihatemoney/translations/tr/LC_MESSAGES/messages.po, ihatemoney/translations/zh_HANS-CN/LC_MESSAGES/messages.po
The limit for displaying "Everyone except …"
instead of the ower's list is completely empirical.
Supersedes #335
=> Add more human "for who?" description.

docs/contributing.rst
=> Add information on how to translate.

ihatemoney/api.py, ihatemoney/tests/tests.py
=> Fixed public project creation flag in API creation #246

CHANGELOG.rst, ihatemoney/templates/statistics.html, ihatemoney/tests/tests.py
Updates:
Remove header and table column of 'Balance' in statistics view
Edited tests to reflect these changes
Fixes #323
=> Statistics view #323

ihatemoney/models.py, ihatemoney/tests/tests.py
SQL query is faster for summing up weights
=> Update models: Bill.pay_each()

ihatemoney/static/css/main.css
To avoid issues likes this, 
let's drop min width for small screens
=> fix(Home): correct responsive width of cards

.isort.cfg, Makefile, docs/conf.py, ihatemoney/api/common.py, ihatemoney/api/v1/resources.py, ihatemoney/forms.py, ihatemoney/history.py, ihatemoney/manage.py, ihatemoney/models.py, ihatemoney/patch_sqlalchemy_continuum.py, ihatemoney/run.py, ihatemoney/tests/tests.py, ihatemoney/utils.py, ihatemoney/web.py, setup.cfg, tox.ini
=> Add isort support.

ihatemoney/default_settings.py
According to https://hosted.weblate.org/projects/i-hate-money/i-hate-money/
these translations are almost complete (69% and 58% currently, but that's
because there have been lots of new strings to translate recently)
=> Add Indonesian and Norwegian to the list of supported languages

.gitignore, docs/contributing.rst, ihatemoney/migrations/versions/cb038f79982e_sqlite_autoincrement.py
=> Fix sqlite only migration.

.gitignore
Show some love for the folks using PyCharm!
=> Add .idea/ folder to gitignore

ihatemoney/templates/history.html, ihatemoney/templates/list_bills.html, ihatemoney/templates/settle_bills.html, ihatemoney/templates/sidebar_table_layout.html, ihatemoney/templates/statistics.html
We also use the currencyformat_nc to show currency formatting everywhere
=> Add a unified balance table for all sidebar pages

ihatemoney/templates/home.html
This is a fix for Issue [#610 ](https://github.com/spiral-project/ihatemoney/issues/610)
I have updated the message and tested locally.
=> Fix: Change tool-tip message for access code

ihatemoney/models.py, ihatemoney/tests/tests.py, ihatemoney/web.py
Fixes #609 by adding a few members and bills to the default test project.
=> Populate the demo project with defaults.

ihatemoney/templates/home.html
This is related to issue #634 .
This is tested locally.
=> fixed bug on tool-tip message

ihatemoney/api/common.py, ihatemoney/forms.py, ihatemoney/history.py, ihatemoney/models.py, ihatemoney/run.py, ihatemoney/tests/tests.py, ihatemoney/utils.py
Some trailing commas were removed because of some black changes.
=> update to black 20.8b1

ihatemoney/conf-templates/ihatemoney.cfg.j2
=> sqlalchemy database uri needs for '/' for local files

Makefile, ihatemoney/migrations/env.py, ihatemoney/patch_sqlalchemy_continuum.py, ihatemoney/run.py, tox.ini
This is the minimal version supported anyway.
=> Set black target to python3.6

Dockerfile
To fix https://github.com/spiral-project/ihatemoney/issues/726
=> disable greenlet c++ test to avoid error #726

ihatemoney/templates/layout.html
=> Navbar change

ihatemoney/forms.py, ihatemoney/web.py, setup.cfg
=> Upgrade WTForms to <2.4

CHANGELOG.rst, README.rst, docs/configuration.rst, docs/installation.rst, docs/upgrade.rst
Also document the new requirement for MariaDB >= 10.3.2
Fixes: #632
Fixes: #743
=> Replace MySQL by MariaDB in all documentation / README / changelog

setup.cfg
=> Bump WTForms dependency

docs/installation.rst, setup.cfg
=> Bump pymysql upper bound to <1.1

docs/configuration.rst, docs/installation.rst
These would have stopped me from making a few mistakes when trying to install.
(After about an hour, I hit some inscrutable SQL error, and decided to use the hosted version, donate, and move on with my life. But hopefully I can make the path a bit clearer for the next person.)
=> Miscellaneous improvements to installation instructions

docs/api.rst
Updated the example API output for "Getting information about the project" in the documentation.
=> update api output (For issue #782)

ihatemoney/translations/fr/LC_MESSAGES/messages.po
=> Fix weblate

ihatemoney/tests/main_test.py
=> Check that project creation via the API doesn't required a captcha.

ihatemoney/tests/budget_test.py, ihatemoney/tests/common/ihatemoney_testcase.py, ihatemoney/web.py
=> Allow connecting to upper-case project IDs.

ihatemoney/api/common.py, ihatemoney/emails.py, ihatemoney/templates/reminder_mail.en.j2, ihatemoney/templates/reminder_mail.fr.j2, ihatemoney/tests/api_test.py, ihatemoney/tests/budget_test.py, ihatemoney/web.py
=> Send an email when the project is created via the API.

ihatemoney/web.py
=> Remove notification showing the id of the project after creation

ihatemoney/web.py
=> Check that language is in the supported list

ihatemoney/templates/showcase.html
=> Fix : use url_for in showcase template.

.github/workflows/test-docs.yml, ihatemoney/utils.py, setup.cfg
It uses a nice tool called vermin: https://pypi.org/project/vermin/
=> Check python compatibility in CI

README.md, docs/installation.md
Following discussion https://github.com/spiral-project/ihatemoney/discussions/997
Regards,
=> Cloud Providers list

ihatemoney/templates/list_bills.html
=> Hide "each" amount when there's only one recipient

ihatemoney/templates/forms.html
=> Add a Cancel Button when editing a bill

ihatemoney/currency_convertor.py, ihatemoney/tests/main_test.py
=> Capture exchange API failures

ihatemoney/forms.py, ihatemoney/tests/budget_test.py
fix https://huntr.dev/bounties/441cc44c-6837-46ec-9b30-52455aa71a2f/
=> Surround email in case of error

ihatemoney/run.py
Ultimately, we should get rid of inline style
For image in data: scheme, I think it's OK for now
Fixes #1055
=> Allow more elements with CSP

ihatemoney/forms.py, ihatemoney/tests/main_test.py
=> Captcha value should be case insensitive on both side (form and l10n values)

ihatemoney/templates/layout.html, ihatemoney/tests/budget_test.py, ihatemoney/web.py
This avoid finding duplicates, and we only need id -> name
also, use a common function to avoid duplicate code
fix #1081
=> Use dict to maintain authenticated projects

ihatemoney/forms.py, ihatemoney/run.py, ihatemoney/templates/layout.html, ihatemoney/tests/budget_test.py, ihatemoney/utils.py, ihatemoney/web.py, setup.cfg
For the moment, it's just the integration of flask-limiter instead of the old and hand-made LoginThrottler.
Open discussion: since we are about to use limiter in more places than admin login, I modified the main layout to display limit breached. But… should we displayed the content block in this case? Or just optionnally, based on some variable?
=> Integrate flask-limiter

docs/installation.md
Thanks to @natim for the issue.
=> [Doc] Include minimal steps to get started.

ihatemoney/history.py, ihatemoney/models.py, ihatemoney/run.py, ihatemoney/static/css/main.css, ihatemoney/templates/edit_project.html, ihatemoney/templates/helpers.js, ihatemoney/templates/list_bills.html, ihatemoney/tests/api_test.py, ihatemoney/tests/budget_test.py, ihatemoney/tests/common/ihatemoney_testcase.py, ihatemoney/tests/history_test.py, ihatemoney/tests/main_test.py
This is a continuation of #1096.
=> Better bill deletion confirmation

ihatemoney/models.py, ihatemoney/monkeypath_continuum.py, setup.cfg
This try to workaround https://github.com/kvesteri/sqlalchemy-continuum/issues/264
It's not really beautiful, but we could then move to sqlalchemy 1.4.
=> Monkeypatching continuum

docs/configuration.md
Fix minimal typo, tripping me (and most likely others) during setup. (e.g. #854)
=> Fixing minimal typo

docker-compose.yml
=> Improve docker-compose file: admin password and volume for database

SECURITY.md
I just discovered this file, and it's out-of-date
=> Update security support status

.github/workflows/lint-and-tests.yml, pyproject.toml
=> fix babel 2.14+ and python 3.12+ setuptools dependency

docs/configuration.md, ihatemoney/default_settings.py, ihatemoney/templates/layout.html, ihatemoney/tests/budget_test.py, ihatemoney/tests/ihatemoney.cfg, ihatemoney/web.py
In browser tabs, I like to see the name of the website. I used the same format as it's done in the feed: https://github.com/spiral-project/ihatemoney/blob/6582e2c0c3b5bd84516715d287e54e26147d09e1/ihatemoney/templates/project_feed.xml#L7
So here is a tiny change, and it's also OK  to close the PR if such a modification is not welcome :)
=> feat: preprend "I Hate Money" to the page title

pyproject.toml, uv.lock
Remove it from the deps as it's not used anymore.
=> Remove flake8

ihatemoney/default_settings.py, ihatemoney/translations/az/LC_MESSAGES/messages.po
I added Azerbaijani Translation
=> I added Azerbaijani Translation

ihatemoney/templates/forms.html
Hi,
I updated the form for editing participants. I added a cancel/back button, and changed the button text to reflect that it's an edit vs add. I believe this makes the app a little easier to navigate, and a little less confusing. 
Thank you
=> UI/navigation changes to in "Edit this participant"
